/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"

// GListeners
GListener glistener;

// GHandles
GHandle ghContainerPage0;
GHandle ghStart;
GHandle ghSave;
GHandle ghPower;
GHandle ghTest;
GHandle ghLabel1;
GHandle ghLabel2;
GHandle ghLabel3;
GHandle ghLabel4;
GHandle ghLabel5;
GHandle ghImagebox1;

// Fonts
font_t dejavu_sans_16;

// Images

static void createPagePage0(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerPage0
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerPage0 = gwinContainerCreate(0, &wi, 0);

	// create button widget: ghStart
	wi.g.show = TRUE;
	wi.g.x = 250;
	wi.g.y = 210;
	wi.g.width = 50;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "Start";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghStart = gwinButtonCreate(0, &wi);

	// create button widget: ghSave
	wi.g.show = TRUE;
	wi.g.x = 180;
	wi.g.y = 210;
	wi.g.width = 50;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "Save";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghSave = gwinButtonCreate(0, &wi);

	// create button widget: ghPower
	wi.g.show = TRUE;
	wi.g.x = 110;
	wi.g.y = 210;
	wi.g.width = 50;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "Power";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghPower = gwinButtonCreate(0, &wi);

	// create button widget: ghTest
	wi.g.show = TRUE;
	wi.g.x = 40;
	wi.g.y = 210;
	wi.g.width = 50;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "Test";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghTest = gwinButtonCreate(0, &wi);

	// Create label widget: ghLabel1
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 20;
	wi.g.width = 60;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "T = -- C";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel1 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel1, FALSE);

	// Create label widget: ghLabel2
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 110;
	wi.g.width = 70;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "F = -- Hz";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel2 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel2, FALSE);

	// Create label widget: ghLabel3
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 50;
	wi.g.width = 70;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "P = -- Pa";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel3 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel3, FALSE);

	// Create label widget: ghLabel4
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 80;
	wi.g.width = 70;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "H = -- %";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel4 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel4, FALSE);

	// Create label widget: ghLabel5
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 160;
	wi.g.width = 100;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "Pw = -- dBm";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel5 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel5, FALSE);

	// create button widget: ghImagebox1
	wi.g.show = TRUE;
	wi.g.x = 130;
	wi.g.y = 20;
	wi.g.width = 160;
	wi.g.height = 145;
	wi.g.parent = ghContainerPage0;
	ghImagebox1 = gwinImageCreate(0, &wi.g);
	gwinImageOpenFile(ghImagebox1, "rsc/graph.bmp");
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerPage0);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerPage0);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DejaVuSans16");

	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);
	gwinSetDefaultStyle(&white, FALSE);
	gwinSetDefaultColor(black_studio);
	gwinSetDefaultBgColor(white_studio);

	// Create all the display pages
	createPagePage0();

	// Select the default display page
	guiShowPage(0);

}

void guiEventLoop(void)
{
	GEvent* pe;

	while (1) {
		// Get an event
		pe = geventEventWait(&glistener, 0);
		switch (pe->type) {
		}

	}
}

