/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "gfx.h"

#include "ch.h"
#include "hal.h"

#include "math.h"

// A set of data points that will be displayed in the graph
static point data[20] = {
    { 10, 0 },
    { 20, 0 },
    { 30, 0 },
    { 40, 0 },
    { 50, 0 },
    { 60, 0 },
    { 70, 0 },
    { 80, 0 },
    { 90, 0 },
    { 100,0 },
    { 110, 0 },
    { 120, 0 },
    { 130, 0 },
    { 140, 0 },
    { 150, 0 },
    { 160, 0 },
    { 170, 0 },
    { 180, 0 },
    { 190, 0 },
    { 200,0 }
};

// A graph styling
static GGraphStyle GraphStyle1 = {
    { GGRAPH_POINT_DOT, 0, Blue },          // Point
    { GGRAPH_LINE_NONE, 2, Gray },          // Line
    { GGRAPH_LINE_SOLID, 0, White },        // X axis
    { GGRAPH_LINE_SOLID, 0, White },        // Y axis
    { GGRAPH_LINE_DASH, 5, Gray, 50 },      // X grid
    { GGRAPH_LINE_DOT, 7, Yellow, 50 },     // Y grid
    GWIN_GRAPH_STYLE_POSITIVE_AXIS_ARROWS   // Flags
};

// Another graph styling
static const GGraphStyle GraphStyle2 = {
    { GGRAPH_POINT_SQUARE, 5, Red },        // Point
    { GGRAPH_LINE_DOT, 2, Blue },           // Line
    { GGRAPH_LINE_SOLID, 0, White },        // X axis
    { GGRAPH_LINE_SOLID, 0, White },        // Y axis
    { GGRAPH_LINE_DASH, 5, Gray, 50 },      // X grid
    { GGRAPH_LINE_DOT, 7, Yellow, 50 },     // Y grid
    GWIN_GRAPH_STYLE_POSITIVE_AXIS_ARROWS   // Flags
};

static THD_WORKING_AREA(waBlink, 128);
static THD_FUNCTION(thdBlink, arg) {

  (void)arg;

  chRegSetThreadName("blinker");
  while (true) {
    palSetPad(GPIOE, 5);
    chThdSleepMilliseconds(500);
    palClearPad(GPIOE, 5);
    chThdSleepMilliseconds(500);
  }
}

static uint8_t i;
static THD_WORKING_AREA(waGenData, 128);
static THD_FUNCTION(thdGenData, arg) {

    (void)arg;

    chRegSetThreadName("generate random data");

    while (true) {
        for(i=19;i>0;i--){
            data[i].y = data[i-1].y;
        }

        data[0].y = rand() % 150;

        gfxSleepMilliseconds(500);
    }
}



int main(int argc, char* argv[])
{
	(void)argc;
	(void)argv;

    GHandle gh;

	gfxInit();

	palSetPadMode(GPIOE,5,PAL_MODE_OUTPUT_PUSHPULL);
	chThdCreateStatic(waBlink, sizeof(waBlink), NORMALPRIO+1, thdBlink, NULL);
    chThdCreateStatic(waGenData, sizeof(waGenData), NORMALPRIO+1, thdGenData, NULL);

	gdispSetBacklight(100);
	gdispSetContrast(100);

    {
        GWindowInit wi;

        wi.show = TRUE;
        wi.x = wi.y = 0;
        wi.width = gdispGetWidth();
        wi.height = gdispGetHeight();
        gh = gwinGraphCreate(0, &wi);
    }

    while(TRUE) {
        gwinClear(gh);
        gwinGraphSetOrigin(gh, gwinGetWidth(gh)/8, gwinGetHeight(gh)/8);
        gwinGraphSetStyle(gh, &GraphStyle1);
        gwinGraphDrawAxis(gh);

        gwinGraphStartSet(gh);
        gwinGraphSetStyle(gh, &GraphStyle2);
        gwinGraphDrawAxis(gh);

        gwinGraphDrawPoints(gh, data, sizeof(data)/sizeof(data[0]));
        gfxSleepMilliseconds(10);
    }

	return 0;
}
